printf:
	gcc test.c ft_itoa.c ../libft/libft.a
ft_itoa:
	# gcc ../string.c ./ft_itoa.c ../libft/libft.a
test2:
	gcc ../*.c ./test2.c  ./ft_itoa.c ../libft/libft.a -o test2 -g
	# ./test2
k:
	gcc mary.c
floats:
	gcc ./test2.c ./ft_itoa.c ../ft_float.c ../libft/libft.a -o floats