printf:
	gcc test.c ft_itoa.c ../libft/libft.a
ft_itoa:
	# gcc ../string.c ./ft_itoa.c ../libft/libft.a
test2:
	gcc ../string.c ../ft_float.c ./test2.c ../utils.c ../t_long_num.c ../t_long_num_util.c ./ft_itoa.c ../libft/libft.a -o test2
	./test2
k:
	gcc mary.c
floats:
	gcc ./test2.c ../utils.c ./ft_itoa.c ../ft_float.c ../libft/libft.a -o floats